import {chromium,webkit} from 'playwright';
import {readFile,writeFile} from 'node:fs/promises';
import {spawn} from 'node:child_process';
import {randomUUID} from 'node:crypto';
import pg from 'pg';
import assert from 'node:assert/strict';
async function reload(page){await page.reload({waitUntil:'commit'});await page.locator('.home-view').waitFor();}
const env=Object.fromEntries((await readFile('.env.local','utf8')).split('\n').filter(l=>l.includes('=')).map(l=>[l.slice(0,l.indexOf('=')),l.slice(l.indexOf('=')+1)]));
assert.equal(new URL(env.DATABASE_URL).hostname,'127.0.0.1');assert.equal(new URL(env.DATABASE_URL).pathname,'/tianna_ui_local');assert.ok(!env.OPENROUTER_API_KEY);
const admin=new pg.Client({connectionString:env.DATABASE_URL});await admin.connect();const schema='flaccid75_browser_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${schema}`);
const uri=new URL(env.DATABASE_URL);uri.hostname=uri.hostname.replace('-pooler','');uri.searchParams.set('options','-c search_path='+schema);const db=new pg.Client({connectionString:uri.toString()});await db.connect();await db.query(await readFile('migrations/001_initial.sql','utf8'));
process.env.PW_TEST_SCREENSHOT_NO_FONTS_READY='1';
const server=spawn('npm',['run','start','--','--port','3085'],{env:{...process.env,...env,DATABASE_URL:uri.toString()},stdio:['ignore','pipe','pipe'],detached:true});let logs='';server.stdout.on('data',b=>logs+=b);server.stderr.on('data',b=>logs+=b);const evidence=[];
try{
 for(let n=0;n<100;n++){try{if((await fetch('http://localhost:3085')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
 for(const [name,engine] of ([['chromium',chromium],['webkit',webkit]].filter(([name])=>!process.env.BROWSER_ENGINE||name===process.env.BROWSER_ENGINE))){
 await db.query(`UPDATE flaccid75_state SET data='{"profile":null,"clock":null,"days":{},"weights":{}}'`);await db.query('DELETE FROM flaccid75_operations');
 const browser=await engine.launch();try{const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,deviceScaleFactor:1,timezoneId:'America/Los_Angeles'});const page=await context.newPage();page.setDefaultTimeout(10000);const requests=[];page.on('request',r=>requests.push({path:new URL(r.url()).pathname,type:r.resourceType(),event:'start'}));page.on('requestfinished',r=>requests.push({path:new URL(r.url()).pathname,event:'done'}));page.on('requestfailed',r=>requests.push({path:new URL(r.url()).pathname,event:'failed'}));
 await page.goto('http://localhost:3085');await page.getByLabel('Passphrase').fill(env.APP_PASSPHRASE);await page.getByRole('button',{name:'Open'}).click();await page.getByRole('button',{name:'kg · cm'}).click();await page.getByLabel('Height · cm').fill('165');await page.getByLabel('Weight · kg',{exact:true}).fill('65');await page.getByLabel('Age',{exact:true}).fill('30');await page.getByRole('button',{name:'Start'}).click();await page.getByRole('checkbox',{name:'Workout complete'}).waitFor();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('flaccid75-v1')).pending.length===0);await page.evaluate(async()=>{await navigator.serviceWorker.ready});await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
 if(name==='webkit'&&process.env.WEBKIT_OFFLINE!=='1')process.kill(-server.pid,'SIGSTOP');else await context.setOffline(true);const started=Date.now();await reload(page);await page.getByRole('checkbox',{name:'Workout complete'}).waitFor();const offlineOpenMs=Date.now()-started;
 await writeFile('evidence/tiannas-place/after/offline-'+name+'-requests.json',JSON.stringify(requests,null,2));const latency=await page.evaluate(()=>new Promise(resolve=>{const button=document.querySelector('[aria-label="Workout complete"]');const start=performance.now();const observer=new MutationObserver(()=>{if(document.querySelector('[aria-label="Workout complete"]')?.getAttribute('aria-checked')==='true'){observer.disconnect();resolve(performance.now()-start);}});observer.observe(button.closest('.row'),{attributes:true,subtree:true,childList:true});button.click();}));
 await page.getByRole('button',{name:'Add a Stanley'}).click();await page.getByRole('checkbox',{name:'Abs complete'}).click();
 const pending=await page.evaluate(()=>JSON.parse(localStorage.getItem('flaccid75-v1')).pending);assert.equal(pending.length,3);await reload(page);assert.equal(await page.getByRole('checkbox',{name:'Workout complete'}).getAttribute('aria-checked'),'true');await page.screenshot({path:`evidence/tiannas-place/after/real-offline-${name}.png`});
 // Lazily loaded pages come from the service worker cache while offline: Settings, the rules and an activity page all render after the offline reload.
 await page.evaluate(()=>{location.hash='you';});await page.getByRole('switch',{name:'Sound cues'}).waitFor();await page.evaluate(()=>{location.hash='rules';});await page.getByText('What a day is').waitFor();await page.evaluate(()=>{location.hash='walk';});await page.getByRole('button',{name:'Start',exact:true}).waitFor();await page.screenshot({path:`evidence/tiannas-place/after/real-offline-rules-${name}.png`});await page.evaluate(()=>{location.hash='';});await page.locator('.home-view').waitFor();await page.getByRole('checkbox',{name:'Workout complete'}).waitFor();
 if(name==='webkit'&&process.env.WEBKIT_OFFLINE!=='1')process.kill(-server.pid,'SIGCONT');else await context.setOffline(false);await page.evaluate(()=>window.dispatchEvent(new Event('online')));await page.waitForFunction(()=>JSON.parse(localStorage.getItem('flaccid75-v1')).pending.length===0);
 const replay=await page.evaluate(async ops=>{const r=await fetch('/api/sync',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(ops)});return {status:r.status,data:await r.json()};},pending);assert.equal(replay.status,200);assert.deepEqual([...replay.data.accepted].sort(),pending.map(o=>o.id).sort());assert.equal(replay.data.rejected.length,0);const current=(await db.query('SELECT data FROM flaccid75_state')).rows[0].data;const day=Object.values(current.days)[0];assert.ok(Math.abs(day.water-30*29.5735295625)<0.01);assert.equal(day.checks.workout,true);assert.equal(day.checks.abs,true);
 // Onboarding stores two changes (profile and units); the three queued offline make five, and the replay adds none.
 const rows=Number((await db.query('SELECT count(*) FROM flaccid75_operations')).rows[0].count);assert.equal(rows,5);
 const pageSize=await page.evaluate(()=>({width:innerWidth,height:innerHeight,scrollHeight:document.documentElement.scrollHeight,bodyScroll:document.body.scrollHeight,pageScrollsInside:document.querySelector('.page').scrollHeight>document.querySelector('.page').clientHeight,sideways:document.documentElement.scrollWidth>innerWidth}));assert.equal(pageSize.height,844);assert.equal(pageSize.scrollHeight,844);assert.equal(pageSize.sideways,false);
 evidence.push({engine:name,offlineColdOpenMs:offlineOpenMs,habitMutationMs:latency,queuedOperations:pending.length,replayedOperations:pending.length,waterMl:day.water,storedOperationRows:rows,pageSize,lazyPagesOffline:['you','rules','walk'],realPostgres:true,realServiceWorker:true,networkBlock:name==='webkit'&&process.env.WEBKIT_OFFLINE!=='1'?'origin server suspended':'browser offline'});await writeFile('evidence/tiannas-place/after/offline-integration.json',JSON.stringify(evidence,null,2));
 }finally{await browser.close();}}
 await writeFile('evidence/tiannas-place/after/offline-integration.json',JSON.stringify(evidence,null,2));console.log(evidence);
}finally{try{process.kill(-server.pid,'SIGCONT');process.kill(-server.pid,'SIGTERM');}catch{}await db.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
